version: '2'
services:
 app: 
  labels:
   - "SERVICE_NAME=app"
  build: .
  environment:
   DB_CONNECTION_URL: "db_connection_url"
   DB_USER: "user"
   DB_PASS: "pass"
  ports:
   - "8080:8080"
   - "8788:8787"
   - "9990:9990"
  image: "norac/base-wildfly"
  volumes:
   - "_log:/opt/jboss/wildfly/standalone/log"
   - "_deployments:/opt/jboss/wildfly/standalone/deployments"
   - "/path/to/runtime/properties:/home/user/config"
volumes:
 # volumes
 _deployments:
 _log:
